mypro/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from myapp import views as myapp_view
urlpatterns = (
    url(r'^$', myapp_view.index, name='index'),
    url(r'^accounts/login/$', myapp_view.login, name='login'),
    url(r'^accounts/logout/$', myapp_view.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^log_query/$', myapp_view.log_query, name='log_query'),
    url(r'^mysql_query/$', myapp_view.mysql_query, name='mysql_query'),
    url(r'^mysql_admin/$', myapp_view.mysql_admin, name='mysql_admin'),
    url(r'^binlog_parse/$', myapp_view.mysql_binlog_parse, name='binlog_parse'),
    url(r'^tb_check/$', myapp_view.tb_check, name='tb_check'),
    url(r'^dupkey_check/$', myapp_view.dupkey_check, name='dupkey_check'),
    url(r'^meta_data/$', myapp_view.meta_data, name='meta_data'),
    url(r'^mysql_exec/$', myapp_view.mysql_exec, name='mysql_exec'),
    url(r'^captcha/',include('captcha.urls')),
    url(r'^sqlcheck/$', myapp_view.inception, name='inception'),
    url(r'^task/$', myapp_view.task_manager, name='task_manager'),
    url(r'^pre_query/$', myapp_view.pre_query, name='pre_query'),
    url(r'^pass_reset/$', myapp_view.pass_reset, name='pass_reset'),
    url(r'^pre_set/$', myapp_view.pre_set, name='pre_set'),
    url(r'^set_dbgroup/$', myapp_view.set_dbgroup, name='set_dbgroup'),
    url(r'^set_ugroup/$', myapp_view.set_ugroup, name='set_ugroup'),
    url(r'^fast_dbset/$', myapp_view.fast_dbset, name='fast_dbset'),
    url(r'^set_dbname/$', myapp_view.set_dbname, name='set_dbname'),
    url(r'^update_task/$', myapp_view.update_task, name='update_task'),
    url(r'^get_rollback/$', myapp_view.get_rollback, name='get_rollback'),
    url(r'^get_single_rollback/$', myapp_view.get_single_rollback, name='get_single_rollback'),
    url(r'^get_tblist/$', myapp_view.get_tblist, name='get_tblist'),
    url(r'^diff/$', myapp_view.diff, name='diff'),
    url(r'^salt/', include('salt.urls')),
    url(r'^mongodb/', include('mongodb.urls')),
    url(r'^chartapi/', include('chartapi.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^passforget/', include('passforget.urls')),
    url(r'^blacklist/', include('blacklist.urls')),
    url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

salt/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    'salt.views',
    # url(r'^$', 'oms.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^api/execute$', 'execute', name='execute'),
    url(r'^salt_exec/$', 'salt_exec', name='salt_exec'),
    url(r'^hardware_info/$', 'hardware_info', name='hardware_info'),
    url(r'^api/getjobinfo$', 'getjobinfo', name='getjobinfo'),
    url(r'^key_con/$', 'key_con', name='key_con'),
    url(r'^hist_salt/$', 'hist_salt', name='hist_salt'),
    url(r'^record_detail/$', 'record_detail', name='record_detail'),
)

myapp/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

read_write = (
    ('read', 'read'),
    ('write', 'write'),
    ('all', 'all'),
    ('idle', 'idle'),
)
read_write_account = (
    ('read', 'read'),
    ('write', 'write'),
    ('all', 'all'),
    ('admin', 'admin'),
)
db_type = (
    ('mysql', 'mysql'),
    ('mongodb', 'write'),
)


class Db_instance(models.Model):
    ip = models.CharField(max_length=30)
    port = models.CharField(max_length=10)
    role = models.CharField(max_length=30, choices=read_write)
    db_type = models.CharField(max_length=30, default='mysql')

    def __unicode__(self):
        return u'%s %s %s' % (self.ip, self.role, self.db_type)

    class Meta:
        unique_together = ("ip", "port")


class Db_name (models.Model):
    dbtag = models.CharField(max_length=30, unique=True)
    dbname = models.CharField(max_length=30)
    instance = models.ManyToManyField(Db_instance, db_constraint=False)
    account = models.ManyToManyField(User, db_constraint=False)

    def __unicode__(self):
        return u'%s %s' % (self.dbtag, self.dbname)


class Db_account(models.Model):
    user = models.CharField(max_length=30)
    passwd = models.CharField(max_length=255)
    role = models.CharField(max_length=30, choices=read_write_account, default='all')
    tags = models.CharField(max_length=30, db_index=True)
    dbname = models.ManyToManyField(Db_name, db_constraint=False)
    account = models.ManyToManyField(User, db_constraint=False)

    def __unicode__(self):
        return u'%s %s' % (self.tags, self.role)


class Db_group(models.Model):
    groupname = models.CharField(max_length=30, unique=True)
    dbname = models.ManyToManyField(Db_name, db_constraint=False)
    account = models.ManyToManyField(User, db_constraint=False)

    def __unicode__(self):
        return self.groupname


class Oper_log(models.Model):
    user = models.CharField(max_length=35)
    ipaddr = models.CharField(max_length=35)
    dbtag = models.CharField(max_length=35)
    dbname = models.CharField(max_length=40)
    sqltext = models.TextField()
    sqltype = models.CharField(max_length=20)
    create_time = models.DateTimeField(db_index=True)
    login_time = models.DateTimeField()

    def __unicode__(self):
        return self.dbtag

    class Meta:
        index_together = ["dbtag", "sqltype", "create_time"]


class Login_log(models.Model):
    user = models.CharField(max_length=35)
    ipaddr = models.CharField(max_length=35)
    action = models.CharField(max_length=20)
    create_time = models.DateTimeField(db_index=True)


class User_profile(models.Model):
    user = models.OneToOneField(User, db_constraint=False)
    select_limit = models.IntegerField(default=200)
    export_limit = models.IntegerField(default=200)
    task_email = models.IntegerField(db_index=True)

    def __unicode__(self):
        return  self.user.username

    class Meta:

        permissions =(('can_mysql_query', 'can see mysql_query view'),
                      ('can_log_query', 'can see log_query view'),
                      ('can_see_execview', 'can see mysql exec view'),
                      ('can_see_inception', 'can see inception view'),
                      ('can_see_metadata', 'can see meta_data view'),
                      ('can_see_mysqladmin', 'can see mysql_admin view'),
                      ('can_export', 'can export csv'),
                      ('can_insert_mysql', 'can insert mysql'),
                      ('can_update_mysql', 'can update mysql'),
                      ('can_delete_mysql','can delete mysql'),
                      ('can_create_mysql', 'can create mysql'),
                      ('can_drop_mysql', 'can drop mysql'),
                      ('can_truncate_mysql', 'can truncate mysql'),
                      ('can_alter_mysql', 'can alter mysql'),
                      ('can_query_mongo', 'can query mongo'),
                      ('can_see_taskview', 'can see task view'),
                      ('can_admin_task', 'can admin task'),
                      ('can_delete_task', 'can delete task'),
                      ('can_update_task', 'can update task'),
                      ('can_query_pri', 'can query pri'),
                      ('can_set_pri', 'can set pri'),
                      ('can_oper_saltapi', 'can oper saltapi'),
                      )


class Upload(models.Model):
    username = models.CharField(max_length=40)
    filename = models.FileField(upload_to='upload_sql')

    def __unicode__(self):
        return self.username


class Task(models.Model):
    user = models.CharField(max_length=35)
    dbtag = models.CharField(max_length=35)
    sqltext = models.TextField()
    create_time = models.DateTimeField(db_index=True)
    update_time = models.DateTimeField()
    status = models.CharField(max_length=20,db_index=True)
    sqlsha = models.TextField()
    sche_time = models.DateTimeField(db_index=True,default='2199-01-01 00:00:00')
    specification = models.CharField(max_length=100,default='')
    operator = models.CharField(max_length=35, default='')
    backup_status = models.SmallIntegerField(default=1)

    def __unicode__(self):
        return self.dbtag
# backup_status
# o donot  backup
# 1 need  backup
# 2


class Incep_error_log(models.Model):
    myid = models.IntegerField()
    stage = models.CharField(max_length= 20)
    errlevel = models.IntegerField()
    stagestatus = models.CharField(max_length=40)
    errormessage = models.TextField()
    sqltext = models.TextField()
    affectrow = models.IntegerField()
    sequence = models.CharField(max_length=30, db_index=True)
    backup_db = models.CharField(max_length=100)
    execute_time = models.CharField(max_length=20)
    sqlsha = models.CharField(max_length=50)
    create_time = models.DateTimeField(db_index=True)
    finish_time = models.DateTimeField()


class MySQL_monitor(models.Model):
    tag = models.CharField(max_length=20)
    monitor = models.SmallIntegerField(default=1)
    instance = models.OneToOneField(Db_instance, db_constraint=False)
    # instance = models.ForeignKey(Db_instance)
    check_longsql = models.SmallIntegerField(default=0)
    longsql_time = models.SmallIntegerField(default=1200)
    longsql_autokill = models.SmallIntegerField(default=0)
    check_active = models.SmallIntegerField(default=0)
    active_threshold = models.SmallIntegerField(default=30)
    # account = models.OneToOneField(Db_account)
    account = models.ForeignKey(Db_account, db_constraint=False)
    check_connections = models.SmallIntegerField(default=0)
    connection_threshold = models.IntegerField(default=1000)
    check_delay = models.SmallIntegerField(default=0)
    delay_threshold = models.IntegerField(default=3600)
    check_slave = models.SmallIntegerField(default=0)
    replchannel = models.CharField(max_length=30, default='0')
    alarm_times = models.SmallIntegerField(default=3)
    alarm_interval = models.SmallIntegerField(default=60)
    mail_to = models.CharField(max_length=255)

    def __unicode__(self):
        return self.tag

    class Meta:
        db_table = 'mysql_monitor'

myapp/templates/previliges/db_group.html
{% extends "include/base.html" %}
{% block title %}
    <title>设置DB_GROUP</title>
{% endblock %}
{% block name %}
    设置DB_GROUP
{% endblock %}
{%block content%}
    {% if info %}
        </br>
        </br>
        <strong> <span style="color:red">{{ info }}</span></strong>
    {% endif %}
    <form role="form" method='post'>
        {% csrf_token %}
        <div class="col-md-2 main ">
            <table >
                <tr>
                    </br>
                    </br>
                    <td>
                        {% if dbgrouplist %}
                            <strong>CHOOSE GROUP</strong> </br>
                            <select class="form-control col-md-1" name = "dbgroup_set">
                                {% for obj in dbgrouplist %}
                                    {% if obj.groupname == groupname %}
                                        <option selected="selected" value ="{{ obj.groupname }}">{{ obj.groupname }}</option>
                                    {% else %}
                                        <option value ="{{ obj.groupname }}">{{ obj.groupname }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        {% endif %}
                    </td>

                </tr>

                <tr>
                    <td>
                        <button type="submit" name='query' class="btn btn-primary" >查询</button>
                        <button type="submit" name='set' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-danger" >设置</button>
                        <button type="submit" name='delete' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-success" >删除</button>
                    </td>
                </tr>
                <tr>

                    <td>
                        </br>
                        <strong>CREATE & SET</strong> </br>
                        {% if groupname %}
                            <input type=="text" class="form-control" maxlength="30" value="{{ groupname }}" placeholder="input name here" name="newname">

                        {% else %}
                            <input type=="text" class="form-control" maxlength="30" placeholder="input name here" name="newname">
                        {% endif %}
                    </td>

                </tr>
                <tr>
                    <td>
                        <button type="submit" name='create' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-info" >创建</button>
                    </td>
                </tr>
            </table>

        </div>
        <div class="col-md-5 main ">
            {% if userlist %}
                </br>
                <strong>CHOOSE USER:</strong> </br>
                <select class="form-control col-md-1" size="10" multiple="multiple" name = "user_set">
                    {% for obj in userlist %}
                        {% if obj.username == public_user %}
                        {% else %}
                            {% if obj in s_userlist %}
                                <option selected="selected" value ="{{ obj.username }}">{{ obj.username }}</option>
                            {% else %}
                                <option value ="{{ obj.username }}">{{ obj.username }}</option>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </select>
            {% endif %}
        </div>
        <div class="col-md-5 main ">
            {% if dbnamelist %}
                </br>
                <strong>CHOOSE DB:</strong> </br>
                <select class="form-control col-md-1" size="10" multiple="multiple" name = "dbname_set">
                    {% for obj in dbnamelist %}
                        {% if obj in s_dbnamelist %}
                            <option selected="selected" value ="{{ obj.dbtag }}">{{ obj.dbtag }}</option>
                        {% else %}
                            <option value ="{{ obj.dbtag }}">{{ obj.dbtag }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            {% endif %}
        </div>
    </form>

{% endblock %}

myapp/templates/previliges/fast_dbset.html
{% extends "include/base.html" %}
{% block title %}
    <title>快速创建DB</title>
{% endblock %}
{% block name %}
    快速创建DB
{% endblock %}
{%block content%}
    {% if info %}
        </br>
        </br>
        <strong> <span style="color:red">{{ info }}</span></strong>
    {% endif %}

    <form role="form" method='post'>
        {% csrf_token %}
        <div class="row">
            <div class="col-md-7 main ">
                <hr />
                <table>
                    <tr>
                        <td>
                            {#                            {% if inslist %}#}
                            <strong>CHOOSE INS OR CREATE NEW</strong> </br>
                            <select class="form-control col-md-3" name = "ins_set">
                                <option value ="">------------------------------</option>
                                {% for obj in inslist %}
                                    {% if obj == insname %}
                                        <option selected="selected" value ="{{ obj.id }}">{{ obj.ip }} + {{ obj.port }} ({{ obj.role }})</option>
                                    {% else %}
                                        <option value ="{{ obj.id }}">{{ obj.ip }} + {{ obj.port }} ({{ obj.role }})</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            {#                            {% endif %}#}
                        </td>

                        <td>
                            </br>

                            <input type=="text" class="form-control" maxlength="30" placeholder="input IP here" name="newinsip">
                        </td>
                        <td>
                            </br>
                            <input type=="text" class="form-control" maxlength="10" placeholder="input PORT here" name="newinsport">

                        </td>
                        <td>
                            </br>
                            <select class="form-control col-md-3"  name="dbtype">
                                <option value="mysql" selected="selected">MySQL</option>
                                <option value="mongodb" >Mongodb</option>
                            </select>

                        </td>
                    </tr>

                </table>

            </div>
        </div>
        <div class="row">
            <div class="col-md-3 main ">
                <hr />
                <strong>INPUT DBNAME WITH IT'S TAG below:</strong>

                <input type=="text" class="form-control" required="required" maxlength="30" placeholder="input Dbtag here (eg:mysql-djangodb)" name="newdbtag">

                <input type=="text" class="form-control" required="required" maxlength="30" placeholder="input Dbname here (eg:djangodb)" name="newdbname">

                <hr />
                <strong>DB_ACCOUNT FOR NORMAL USE: </strong>
                <input type=="text" class="form-control" maxlength="30" placeholder="input username here" name="newname_all">
                <input type=="text" class="form-control" maxlength="20" placeholder="input password here" name="newpass_all">
                <hr />

                <strong>DB_ACCOUNT FOR USING INCEPTION (optional):  </strong>
                <input type=="text" class="form-control" maxlength="30" placeholder="input username here" name="newname_admin">
                <input type=="text" class="form-control" maxlength="20" placeholder="input password here" name="newpass_admin">
                <button type="submit" name='create' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-info" >创建</button>

            </div>
        </div>

    </form>

{% endblock %}

myapp/templates/previliges/pass_reset.html
{% extends "include/base.html" %}
{% block title %}
    <title>密码重置</title>
{% endblock %}
{% block name %}
    欢迎使用密码重置功能
{% endblock %}
{%block content%}
    <hr />
    <span id="errorpwd" style="color: #eea236" >{{ info }}</span>

    <form role="form" method='post'>
        {% csrf_token %}


        <div class="col-md-2 main ">
            <input id="id_passwd" type="password" class="form-control" maxlength="25" placeholder="type new password here" name="passwd" onkeydown="clearstage()">

            <input id="id_repasswd" type="password" class="form-control" maxlength="25" placeholder="retype password here" name="repasswd" onkeydown="clearstage()" >

            <button id="id_button" type="submit" name='set' onclick="return checkPass();"  class="btn btn-danger" >重置</button>
        </div>
    </form>
{#    <div class="col-md-11">#}
{#        <div id="map" style="width:1000px;height:500px"></div>#}
{#    </div>#}
{#    <script  src="http://api.map.baidu.com/api?v=2.0&ak=zhskfLsPCGPrPQvGb2WsL2mGZsfGO9XT&callback=initialize"></script>#}
{#    <script type="text/javascript">#}
{#        function getLocation(){#}
{#            var options={#}
{#                enableHighAccuracy:true,#}
{#                maximumAge:1000#}
{#            }#}
{#            if(navigator.geolocation){#}
{#                //浏览器支持geolocation#}
{#                navigator.geolocation.getCurrentPosition(onSuccess,onError,options);#}
{##}
{#            }else{#}
{#                //浏览器不支持geolocation#}
{#                alert("not support");#}
{#            }#}
{#        }#}
{##}
{#        function onSuccess(position) {#}
{#            var longitude =position.coords.longitude;#}
{#            var latitude = position.coords.latitude;#}
{#            var mp = new BMap.Map('map');#}
{#            mp.centerAndZoom(new BMap.Point(longitude, latitude), 14);#}
{#            mp.enableScrollWheelZoom();#}
{#            mp.addControl(new BMap.NavigationControl());#}
{#            mp.addControl(new BMap.ScaleControl());#}
{#            mp.addControl(new BMap.OverviewMapControl());#}
{#            mp.addControl(new BMap.MapTypeControl());#}
{#        }#}
{#        function onError(error){#}
{#            switch(error.code){#}
{#                case 1:#}
{#                    alert("位置服务被拒绝");#}
{#                    break;#}
{##}
{#                case 2:#}
{#                    alert("暂时获取不到位置信息");#}
{#                    break;#}
{##}
{#                case 3:#}
{#                    alert("获取信息超时");#}
{#                    break;#}
{##}
{#                case 4:#}
{#                    alert("未知错误");#}
{#                    break;#}
{#            }#}
{##}
{#        }#}
{#        window.onload = getLocation;#}
{#    </script>#}


    <script>
        function clearstage () {
            document.getElementById("errorpwd").innerText = "";

        }
        function checkPass() {
            var pwd1 = document.getElementById("id_passwd").value;
            var pwd2 = document.getElementById("id_repasswd").value;
            if (pwd1.length < 8){
                document.getElementById("errorpwd").innerText = "密码长度至少8位";
                return false;
            }
            if (pwd1 != pwd2) {
                document.getElementById("errorpwd").innerText = "两次密码输入不一致";
                return false;
            }
            return true;
        }
        {#        function checksame() {#}
        {#            var pwd1 = document.getElementById("id_passwd").value;#}
        {#            var pwd2 = document.getElementById("id_repasswd").value;#}
        {##}
        {#            if (pwd1 != pwd2 && pwd1.length != 0) {#}
        {#                document.getElementById("errorpwd").innerText = "两次输入密码不一致";#}
        {#            }#}
        {#            else#}
        {#            {#}
        {#                document.getElementById("errorpwd").innerText = "";#}
        {#            }#}
        {#        }#}


    </script>
{% endblock %}

myapp/templates/previliges/pre_set.html
{% extends "include/base.html" %}
{% block title %}
    <title>用户账户</title>
{% endblock %}
{% block name %}
    用户权限设置
{% endblock %}
{%block content%}
    {% if info %}
        </br>
        </br>
        <strong> <span style="color:red">{{ info }}</span></strong>
    {% endif %}
    <form role="form" method='post'>
        {% csrf_token %}
        <table >
            <tr>
                </br>
                </br>
                <td>
                    <strong>CHOOSE USERNAME:</strong>
                    <select class="form-control col-md-1" name = "account">
                        {% for obj in userlist %}
                            {% if obj.username == username %}
                                <option selected="selected" value ="{{ obj.username }}">{{ obj.username }}</option>
                            {% else %}
                                <option value ="{{ obj.username }}">{{ obj.username }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>
                    <button type="submit" name='query' class="btn btn-primary" >查询</button>
                    <button type="submit" name='set' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-danger" >设置权限</button>
                    <button type="submit" name='reset' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-success" >用户权限清空</button>
                    <button type="submit" name='delete' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-default" >删除用户</button>

                </td>
            </tr>
            <tr>

                {% if mail %}
                    <td>
                        </br>
                        <input type=="text" class="form-control" maxlength="60" value="{{ mail }}" placeholder="input email here" name="newmail">
                    </td>
                {% else %}
                    <td>
                        </br>
                        <input type=="text" class="form-control" maxlength="60" placeholder="input email here" name="newmail">
                    </td>
                {% endif %}
                {% if username %}
                    <td>
                        </br>
                        <input type=="text" class="form-control" maxlength="30" value="{{ username }}" placeholder="input username here" name="newname">
                    </td>
                {% else %}
                    <td>
                        </br>
                        <input type=="text" class="form-control" maxlength="30" placeholder="input username here" name="newname">
                    </td>
                {% endif %}


                <td>
                    </br>
                    <input type=="text" class="form-control" maxlength="20" placeholder="input password here" name="newpasswd">
                </td>



            </tr>
            <tr>
                <td>
                    <button type="submit" name='create' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-info" >创建账号</button>
                </td>
            </tr>
        </table>

        {% if usergroup %}
            </br>
            <strong>CHOOSE USERGROUP FOR USER :</strong>
            <select class="form-control col-md-1" multiple="multiple" size=10 name = "user_group">
                {% for obj in usergroup %}
                    {% if obj in usergp %}
                        <option selected = "selected" value ="{{ obj }}">{{ obj }}</option>
                    {% else %}
                        <option value ="{{ obj }}">{{ obj }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        {% endif %}
        </br>
        <strong>CHOOSE DBGROUP FOR USER :</strong>
        <table id="mytable" class="table table-condensed" border="1">
            <thead>
            <tr class="danger">
                <th>ID</th>
                <th>GROUP_NAME</th>
                <th>DBLIST</th>
                <th>USERACCOUNT</th>
                <th>勾选GROUP</th>
            </tr>
            </thead>
            <tbody  >
            {% for item in grouplist %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.groupname }}</td>
                    <td>
                        {% for i in item.dbname.all %}
                            {% if forloop.counter < 9 %}
                                {{i.dbtag}}  + {{ i.dbname }} </br>
                            {% elif forloop.counter == 9 %}
                                ...
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for i in item.account.all %}
                            {% if forloop.counter < 9 %}
                                {{i.username}} </br>
                            {% elif forloop.counter == 9 %}
                                ...
                            {% endif %}
                        {% endfor %}
                    </td>
                    {% if item in dbgp %}
                        <td><input type="checkbox" checked="1" size="100" name="choosedlist" value={{ item.id }}></td>
                    {% else %}
                        <td><input type="checkbox" size="100" name="choosedlist" value={{ item.id }}></td>
                    {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>


        {#                    <select class="form-control col-md-1" multiple="multiple" name = "grouplist" size="10">#}
        {#                        {% for obj in grouplist %}#}
        {#                            <option value ="{{ obj }}">{{ obj }}</option>#}
        {#                        {% endfor %}#}
        {#                    </select>#}
        {% if dblist %}
            </br>
            <strong>CHOOSE DB FOR USER (optional) :</strong>
            <select class="form-control col-md-1" multiple="multiple" size=10 name = "user_dblist">
                {% for obj in dblist %}
                    {% if obj in userdblist %}
                        <option selected = "selected" value ="{{ obj.dbtag }}">{{ obj.dbtag }}</option>
                    {% else %}
                        <option value ="{{ obj.dbtag }}">{{ obj.dbtag }}</option>
                    {% endif %}
                {% endfor %}
            </select>
        {% endif %}

    </form >


{% endblock %}
{% block script %}
    {% include "include/pagejump/pagejump.html" %}
{% endblock %}