blacklist/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    'blacklist.views',
    url(r'^blist/$', 'blist', name='blist'),
    url(r'^bl_delete/$', 'bl_delete', name='bl_delete'),
    url(r'^bl_edit/$', 'bl_edit', name='bl_edit'),
)

mypro/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from myapp import views as myapp_view
urlpatterns = (
    url(r'^$', myapp_view.index, name='index'),
    url(r'^accounts/login/$', myapp_view.login, name='login'),
    url(r'^accounts/logout/$', myapp_view.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^log_query/$', myapp_view.log_query, name='log_query'),
    url(r'^mysql_query/$', myapp_view.mysql_query, name='mysql_query'),
    url(r'^mysql_admin/$', myapp_view.mysql_admin, name='mysql_admin'),
    url(r'^binlog_parse/$', myapp_view.mysql_binlog_parse, name='binlog_parse'),
    url(r'^tb_check/$', myapp_view.tb_check, name='tb_check'),
    url(r'^dupkey_check/$', myapp_view.dupkey_check, name='dupkey_check'),
    url(r'^meta_data/$', myapp_view.meta_data, name='meta_data'),
    url(r'^mysql_exec/$', myapp_view.mysql_exec, name='mysql_exec'),
    url(r'^captcha/',include('captcha.urls')),
    url(r'^sqlcheck/$', myapp_view.inception, name='inception'),
    url(r'^task/$', myapp_view.task_manager, name='task_manager'),
    url(r'^pre_query/$', myapp_view.pre_query, name='pre_query'),
    url(r'^pass_reset/$', myapp_view.pass_reset, name='pass_reset'),
    url(r'^pre_set/$', myapp_view.pre_set, name='pre_set'),
    url(r'^set_dbgroup/$', myapp_view.set_dbgroup, name='set_dbgroup'),
    url(r'^set_ugroup/$', myapp_view.set_ugroup, name='set_ugroup'),
    url(r'^fast_dbset/$', myapp_view.fast_dbset, name='fast_dbset'),
    url(r'^set_dbname/$', myapp_view.set_dbname, name='set_dbname'),
    url(r'^update_task/$', myapp_view.update_task, name='update_task'),
    url(r'^get_rollback/$', myapp_view.get_rollback, name='get_rollback'),
    url(r'^get_single_rollback/$', myapp_view.get_single_rollback, name='get_single_rollback'),
    url(r'^get_tblist/$', myapp_view.get_tblist, name='get_tblist'),
    url(r'^diff/$', myapp_view.diff, name='diff'),
    url(r'^salt/', include('salt.urls')),
    url(r'^mongodb/', include('mongodb.urls')),
    url(r'^chartapi/', include('chartapi.urls')),
    url(r'^monitor/', include('monitor.urls')),
    url(r'^passforget/', include('passforget.urls')),
    url(r'^blacklist/', include('blacklist.urls')),
    url(r'^site_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

salt/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    'salt.views',
    # url(r'^$', 'oms.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^api/execute$', 'execute', name='execute'),
    url(r'^salt_exec/$', 'salt_exec', name='salt_exec'),
    url(r'^hardware_info/$', 'hardware_info', name='hardware_info'),
    url(r'^api/getjobinfo$', 'getjobinfo', name='getjobinfo'),
    url(r'^key_con/$', 'key_con', name='key_con'),
    url(r'^hist_salt/$', 'hist_salt', name='hist_salt'),
    url(r'^record_detail/$', 'record_detail', name='record_detail'),
)

blacklist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Tb_blacklist(models.Model):
    dbtag = models.CharField(max_length=255, unique=True)
    tbname = models.TextField(max_length=255)
    user_permit = models.ManyToManyField(User, db_constraint=False)

    def __unicode__(self):
        return self.dbtag

    class Meta:
        db_table = 'tb_blacklist'

blacklist/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from blacklist.models import Tb_blacklist
from django.contrib.auth.decorators import login_required,permission_required
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from myapp.models import Db_name
from myapp.etc.config import public_user

# Create your views here.


@login_required(login_url='/accounts/login/')
@permission_required('myapp.can_set_pri', login_url='/')
def blist(request):
    page_size = 10
    all_record = Tb_blacklist.objects.all().order_by('id')
    paginator = Paginator(all_record, page_size)
    try:
        page = int(request.GET.get('page', 1))
    except ValueError:
        page = 1
    try:
        posts = paginator.page(page)
    except (EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blist.html', locals())


@login_required(login_url='/accounts/login/')
@permission_required('myapp.can_set_pri', login_url='/')
def bl_delete(request):
    try:
        myid = int(request.GET['dbid'])
        db = Tb_blacklist.objects.get(id=myid)
        db.delete()
    except:
        pass
    finally:
        return HttpResponseRedirect("/blacklist/blist/")


@login_required(login_url='/accounts/login/')
@permission_required('myapp.can_set_pri', login_url='/')
def bl_edit(request):
    userlist = User.objects.exclude(username=public_user).all().order_by('username')
    if request.method == 'GET':
        try:
            myid = int(request.GET['dbid'])
            edit_db = Tb_blacklist.objects.get(id=myid)
        except:
            pass
    elif request.method == 'POST':
        try:
            info = "set ok"
            if request.POST.has_key('set'):
                myid = int(request.POST['set'])
                edit_db = Tb_blacklist.objects.get(id=myid)
                dbtag = request.POST['setdbtag'][:30]
                if Tb_blacklist.objects.filter(dbtag=dbtag).exclude(id=myid).all()[:1]:
                    info = "this dbtag already settled"
                    return render(request, 'bl_edit.html', locals())
                edit_db.dbtag = dbtag
                edit_db.tbname = request.POST['settbname'][:300]

                for i in edit_db.user_permit.all():
                    edit_db.user_permit.remove(i)
                for i in User.objects.filter(username__in=request.POST.getlist('choose_user')).all():
                    edit_db.user_permit.add(i)
                edit_db.save()
            elif request.POST.has_key('create'):
                dbtag = request.POST['setdbtag']
                if not Db_name.objects.filter(dbtag=dbtag).all()[:1]:
                    info = "dbtag not exists"
                    return render(request, 'bl_edit.html', locals())
                edit_db = Tb_blacklist(dbtag=dbtag, tbname=request.POST['settbname'][:300])
                edit_db.save()
                for i in User.objects.filter(username__in=request.POST.getlist('choose_user')).all():
                    edit_db.user_permit.add(i)
                edit_db.save()

        except Exception as e:
            info = "set failed"
    return render(request, 'bl_edit.html', locals())

blacklist/templates/bl_edit.html
{% extends "include/base.html" %}
{% block title %}
    <title>BlackList Edit</title>
{% endblock %}
{% block name %}
    黑名单设置
{% endblock %}
{%block content%}
    <div class="row">
        <div class="col-md-12 main ">
            <button onclick="openpage('{% url 'blist' %}')"  class="btn btn-info">返回</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 main ">
            {% if info %}
                <strong> <span style="color:red">{{ info }}</span></strong>
            {% endif %}

            <form role="form" method='post'>
                {% csrf_token %}
                {% if edit_db %}
                    <table id="mytable" class="table table-bordered">
                        <tr>
                            <td>
                                ID
                            </td>
                            <td>
                                {{ edit_db.id }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                DB标签
                            </td>
                            <td>
                                <input type=="text" name="setdbtag" class="form-control" maxlength="30" placeholder="input Dbtag" value="{{ edit_db.dbtag }}" >
                            </td>
                        </tr>
                        <tr>
                            <td>
                                限制查询表(多个表名之间以逗号分隔)
                            </td>
                            <td>
                                <textarea placeholder="输入表名，多个表名之间以逗号分隔" cols="50" id="id_tbname" maxlength="300" name="settbname" rows="10">{{ edit_db.tbname }}</textarea>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                允许访问用户名单
                            </td>
                            <td>
                                <select class="form-control col-md-1" multiple="multiple" size="10"  name = "choose_user">
                                    {% for user in userlist %}
                                        {% if user in edit_db.user_permit.all  %}
                                            <option selected="selected" value ="{{ user.username }}">{{ user.username }}</option>
                                        {% else %}
                                            <option value ="{{ user.username }}">{{ user.username }}</option>

                                        {% endif %}
                                    {% endfor %}
                                </select>

                            </td>
                        </tr>

                    </table>

                    <button type="submit" name='set' onclick="return confirm('PLEASE COMFIRM')" value="{{ edit_db.id }}" class="btn btn-success" >设置</button>

                {% else %}
                    <table id="mytable" class="table table-bordered">
                        <tr>
                            <td>
                                DB标签
                            </td>
                            <td>
                                <input type=="text" name="setdbtag" class="form-control" maxlength="30" placeholder="input Dbtag"  >
                            </td>
                        </tr>
                        <tr>
                            <td>
                                限制查询表(多个表名之间以逗号分隔)
                            </td>
                            <td>
                                <textarea placeholder="输入表名，多个表名之间以逗号分隔" cols="50" id="id_tbname" maxlength="300" name="settbname" rows="10"></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                允许访问用户名单
                            </td>
                            <td>
                                <select class="form-control col-md-1" multiple="multiple" size="10"  name = "choose_user">
                                    {% for user in userlist %}
                                        <option value ="{{ user.username }}">{{ user.username }}</option>
                                    {% endfor %}
                                </select>

                            </td>
                        </tr>

                    </table>




                    <button type="submit" name='create' onclick="return confirm('PLEASE COMFIRM')"  class="btn btn-success" >创建</button>

                {% endif %}

            </form >
        </div>
    </div>


{% endblock %}
{% block script %}

{% endblock %}

blacklist/templates/blist.html
{% extends "include/base.html" %}
{% block title %}
    <title>Query BlackList</title>
{% endblock %}
{% block name %}
    查询页面黑名单设置
{% endblock %}
{%block content%}
    <div class="row">
        <div class="col-md-12 main ">
            <button onclick="openpage('{% url 'bl_edit' %}')" class="btn btn-primary" >新增</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 main ">
            {% if posts %}
                <table  id="mytable" class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>DB标签</th>
                        <th>限制查询表</th>
                        <th>允许访问用户名单</th>
                        <th></th>
                    </thead>
                    <tbody>
                    {% for item in posts %}
                        <tr>
                            <td>
                                {{ item.id }}
                            </td>
                            <td>
                                {{ item.dbtag }}
                            </td>
                            <td>
                                {{ item.tbname }}
                            </td>
                            <td>
                                {% for user in item.user_permit.all %}
                                    {{ user.username }},
                                {% endfor %}
                            </td>
                            <td colspan="2">
                                <a href="{% url 'bl_edit' %}?dbid={{ item.id }}" title="修改" > <span class="glyphicon glyphicon-pencil" ></span> </a>
                                <a href="{% url 'bl_delete' %}?dbid={{ item.id }}" onclick="return confirm('PLEASE COMFIRM')" title="删除" > <span class="glyphicon glyphicon-minus" ></span> </a>
                            <td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <nav>
                    <ul class="pager">
                        {% if posts.has_previous %}
                            <li class="previous"><a href="?page={{ posts.previous_page_number }}"><span aria-hidden="true">&larr;</span>前一页</a></li>
                        {% else %}
                            <li class="previous disabled"><a><span aria-hidden="true">&larr;</span>前一页</a></li>
                        {% endif %}
                        <li><a>第{{ posts.number }}页/共{{ posts.paginator.num_pages }}页</a></li>
                        {% if posts.has_next %}
                            <li class="next"><a href="?page={{ posts.next_page_number }}">下一页<span aria-hidden="true">&rarr;</span></a></li>
                        {% else %}
                            <li class="next disabled"><a>下一页<span aria-hidden="true">&rarr;</span></a></li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-10 main">

        </div>

    </div>
    <hr />


{% endblock %}
{% block script %}

{% endblock %}